# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
      - run: npm run check

      # ---
      # cleaning up the code if it's a failure
      - name: Format and create comments with suggestions
        if: ${{ failure() }}
        run: npm run format
      - uses: devops-infra/action-commit-push@v0.5
        if: ${{ failure() }}
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          commit_message: 'Made your code *Prettier* heheh'
          force: false
          target_branch: '${{ $GITHUB_REF_NAME }}'
